### ISSUE TITLE
Broken Dart2Js

### ISSUE THREAD

**Issue by Andruj** [ntaoo/ng2_g_signin#1]
I am using this signin, which works fine in the example, but when I use a newer version of dart2js it breaks.

[Warning from Dart2JS on aurora|web/main.dart]:
packages/ng2_g_signin/src/google_signin.template.dart:51:10:
'List' is not assignable to 'Params'.
    init([],[_el_0],[]);
         ^^
[Info from Dart2JS on aurora|web/main.dart]:
packages/ng2_g_signin/src/google_signin_js/gapi/auth2.dart:7:1:
This is the method declaration.
external GoogleAuth init(Params params);

It seems that the init function is not matching the parameters from dart.

**Comment by ntaoo** [comment]
O.K, I will look into this soon.

**Comment by ntaoo** [comment]
I suspect that upgrading angular2 from beta.22 to 2.0.0 causes the error.

**Comment by ntaoo** [comment]
@Andruj Please tell me if you still get the same problem after upgrading this package to 0.3.1.
